#!/bin/bash
function main {
	print_heading
	if [ $(ls | grep master.zip) ]; then
		print_one "entferne alte Dateien..."
		rm -f master.zip
	fi
	print_heading
	print_one "Teste die Internetverbindung...."
	if [ "ping -c archlinux.org" ]
	then
		continue
	else
		print_heading
		print_one "Kein Internetzugang versuche es mit Wireless"
		wifi-menu &>/dev/null
		main
	fi
	print_heading
	print_one "Lade Datei..."
	wget -q https://github.com/montygood/monty/archive/master.zip --show-progress
	if [ $(ls | grep master.zip) ]; then
		print_one "entpacke Dateien"
		unzip -o master.zip
		cp -r monty-master/* .
		rm -rf monty-master
		rm -f *.zip
		chmod +x inst.sh
		./inst.sh
	else
		print_one "konnte Datei nicht herunterladen"
		print_one "reboot eingeben um neu zu starten"
		exit
	fi
}
function print_heading {
	clear
	T_COLS=$(tput cols)
	tput cup 1 $(((T_COLS/2)-18))
	tput bold
	printf "%-s\n" "$Backtitle"
	echo ""
	tput sgr0
}
function print_one {
	width=$(tput cols)
	EMPTY=" "
	lov=${#1}
	if [ ${lov} -lt ${width} ]; then
		stpt=$(( ($width - $lov) / 2 ))
		EMPTY="$(printf '%*s' $stpt)"
	fi
	echo "$EMPTY $1"
}
Backtitle="Willkommen zum Monty Arch-installer."
loadkeys de_CH-latin1
main
