#!/bin/bash
# Funktionen
function main {
	print_heading
	check_internet
	Service="N"
	Counter=0
	while [ "$Service" = "N" ]
		do
			Counter=$((Counter+1))
			if [ $Counter -gt 3 ]; then
				error_exit
			fi
			if [ $(ls | grep master.zip) ]; then
				rm -f master.zip
			fi
			print_one "Lade Datei..."
			wget -q https://github.com/montygood/monty/archive/master.zip --show-progress
			if [ $(ls | grep master.zip) ]; then
				print_one "entpacke Dateien"
				unzip -o master.zip
				cp -r monty-master/* .
				FileCheck=$(ls | grep monty)
				if [ -z "$FileCheck" ]; then
					continue
				fi
			else
				continue
			fi
			Service="Y"
	done
	rm -rf monty-master
	rm -f *.zip
	while [ "$Service" = "N" ]
		do
			Counter=$((Counter+1))
			if [ $Counter -gt 3 ]; then
				error_exit
			fi
			if [ -f inst.sh ]; then
				Service="Y"
			fi
	done
	chmod +x inst.sh
	./inst.sh
}
function check_internet {
	while [ "$Service" = "N" ]
	do
		print_one "Teste die Internetverbindung,"
		check_connection
		case "$Service" in
			"N") print_one "Sorry, installation kann ohne Internet nicht starten."
				 exit
				 ;;
			*)   print_one "Lade das aktuelle Script von Github.com ..."
				 print_heading
				 Service="Y"
		esac
	done
}
function check_connection {
	while [ "$Service" = "N" ]
	do
		ping -q -c3 archlinux.org &>/dev/null
		PingTest=$?
		if [ ${PingTest} -ne 0 ]; then
			print_one "versuche es mit Wireless"
			wifi-menu &>/dev/null
			ping -q -c3 archlinux.org &>/dev/null
			PingTest=$?
			if [ ${PingTest} -ne 0 ]; then
				print_heading
				print_one "Kein Internetzugang."
				print_one "versuche es mit einem Netzwerkkabel."
				aligned_prompt "erneut Versuchen? (J/n): "
				if [ "$Response" = "N" ] || [ "$Response" = "n" ]; then
					exit
				else
					continue
				fi
			else
				Service="Y"
			fi
		else
			Service="Y"
		fi
	done
}
function print_heading {
	clear
	T_COLS=$(tput cols)
	tput cup 1 $(((T_COLS/2)-20))
	tput bold
	printf "%-s\n" "$Backtitle"
	echo ""
	tput sgr0
}
function print_one {
	width=$(tput cols)
	EMPTY=" "
	lov=${#1}
	if [ ${lov} -lt ${width} ]; then
		stpt=$(( ($width - $lov) / 2 ))
		EMPTY="$(printf '%*s' $stpt)"
	fi
	echo "$EMPTY $1"
}
function aligned_prompt {
	T_COLS=$(tput cols)
	lov=${#1}
	if [ ${lov} -lt ${T_COLS} ]; then
		stpt=$(( ($T_COLS - $lov) / 2 ))
	elif [ ${lov} -gt ${T_COLS} ]; then
		stpt=0
	else
		stpt=$(( ($T_COLS - 10) / 2 ))
	fi
	EMPTY="$(printf '%*s' $stpt)"
	read -p "$EMPTY $1" Response
}
function error_exit {
	print_one "kann das Scripts nicht herunterladen."
	aligned_prompt "erneut Versuchen? (J/n): "
	if [ "$Response" = "N" ] || [ "$Response" = "n" ]; then
		exit
	else
		Counter=0
	fi
}
# Declare & initialise variablen
Backtitle="Willkommen beim Monty installer von Arch Linux."
PingTest=""
Chosen="cli"
Counter=0
Service="N"
loadkeys de_CH-latin1
main
